# Generated by Django 5.1.1 on 2024-10-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0002_youtubeprofile_playlistid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeprofile',
            name='playlistid',
            field=models.CharField(null=True),
        ),
    ]
